### ISSUE TITLE
Where is the main bsi file?

### ISSUE THREAD

**Issue by wenyongzhe1992** [BSData/team-yankee#12]
Hi.
I am trying to find the url of the bsi file. However, I didn't see one on the data files page (http://battlescribedata.appspot.com/#/repos).
Thanks

**Comment by amis92** [comment]
Hi. For AppSpot site, there's no index.bsi available.

What do you need it for? It's a legacy distribution system.

**Comment by wenyongzhe1992** [comment]
I just want to load the TY data from Battle Scribe. Well, I just found it in the software now, but yesterday I did not see this option. Thanks
