### ISSUE TITLE
[Anon] Bug report: Soviet.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/team-yankee#26]
**File:** Soviet.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Soviet shock motor rifle platoon has incorrect points cost. 6x ak-74 team option should be 24 points, 4x ak-74 team should be 15 points. Currently both options are 24 points.

**Comment by Trommelbohne** [comment]
Fixed in release 1.0.20
Thanks for finding it.
