### ISSUE TITLE
[Anon] Bug report: Soviet.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/team-yankee#28]
**File:** Soviet.catz

**BattleScribe version:** 2.03.25

**Platform:** Windows

**Dropbox:** No

**Description:** Hind Support Company is missing points for upgraded Spiral-9 missiles and the attached Infantry are missing points for RPG-7VR upgrade

**Comment by Trommelbohne** [comment]
Fixed in release 1.0.21
Thanks for finding and reporting ❤
