### ISSUE TITLE
[Anon] Bug report: Leopard (West German Forces).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/team-yankee#32]
**File:** Leopard (West German Forces).catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Would it be possible to get an update for the new West German book?

**Comment by Trommelbohne** [comment]
As soon as I can get my hands on it, I will add it.

**Comment by Nabesoft** [comment]
Hi @Trommelbohne, is there still an intention to update to the new West German book? I can provide the content if required as I have the book. :)
