### ISSUE TITLE
Bug report: American.catz

### ISSUE THREAD

**Issue by Quasihodo** [BSData/team-yankee#35]
RDF/LT Assault Gun Platoon Unit Size should be 2x/3x/4x, now it is 2x/4x/4x

![Bug](https://user-images.githubusercontent.com/89463534/130623848-9274b2a6-c43d-4286-86c3-9f61d974405e.jpg)

**Comment by Trommelbohne** [comment]
Thank you for reporting this bug ❤

It is fixed in Release 1.0.24.
Repo will update within the next 24 hours.
