### ISSUE TITLE
Would like to contribute, opened Pull Request for West Geman Catalogue

### ISSUE THREAD

**Issue by Trommelbohne** [BSData/team-yankee#4]
Hi there,
I would like to contribute effort towards the Team Yankee Battlescribe Data Catalogues. I already created one for the West Germans (based on "Leopard" Source Book), using the concepts established in the American Catalogue.  There is a Pull request open for that.

Best regards, Nico

**Comment by amis92** [comment]
@toasterfree you seem to be the active maintainer, opinion?

**Comment by toasterfree** [comment]
Thank you for reaching out. I completed the merge request

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by toasterfree** [comment]
I am happy to have someone else help out where I am missing information right now. All help is appreciated.
