### ISSUE TITLE
[Anon] Bug report: Free Nations.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/team-yankee#42]
**File:** Free Nations.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** Yes

**Description:** Netherlands m106 120mm mortar platoon is showing as no cost in ypr-765 pantserinfanterie compagnie. It should be 2 pts for 2 and 3 points for 3 per free nations page 55.

**Comment by Trommelbohne** [comment]
Fixed
